"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Activity, BarChart3, Bot, Building2, Download, FileText, FolderOpen, Landmark, Loader2, MessageSquareText, Search, ShieldCheck, TrendingUp, Users, Briefcase } from "lucide-react";
import { BusinessModelSection } from "./BusinessModelSection";

const API = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000";
type CoverageTier = "full" | "unverified" | "price_only";
type Tab = "overview" | "business-model" | "financials" | "kpis" | "valuation" | "peers" | "announcements" | "filings" | "ai" | "report";
interface UniverseEntry { symbol:string; name:string; sector:"FERTILIZER"|"CEMENT"; coverage_tier:CoverageTier; index_weight:number|null; issuer_id:number; }
interface Universe { as_of:string; count:number; tier_counts:Record<string,number>; sector_counts:Record<string,number>; entries:UniverseEntry[]; }
interface Point { period_end:string; value:number; unit?:string; period_type?:string; }
interface Ratio { name:string; category:string; unit:string; formula:string; values:Point[]; }
interface Peer { id:number; symbol:string; name:string; sector:string; market_cap:number|null; eps:number|null; roe:number|null; debt_to_equity:number|null; net_profit_margin:number|null; coverage_status:string; }
interface Workspace { ticker:string; generated_at:string; coverage_tier:CoverageTier; evidence:{source_count:number;announcement_count:number;financial_series_count:number;ratio_series_count:number;fundamentals_renderable:boolean}; overview:{issuer:{name:string;short_name:string|null;sector_name:string;business_description:string|null;website:string|null;auditor:string|null;fiscal_year_end_month:number|null;establishment_year:number|null};data_delay_notice:string;symbol:string;security_id:number|null;free_float_pct:number|null;financials:Record<string,Point[]>;ratios:Record<string,Ratio>;payouts:{action_type:string;effective_date:string;ratio_or_amount:number|null}[];announcements:{id:number;title:string;category:string;published_at:string;summary:string|null;source_url:string|null}[];sources:{document_type:string;source_tier:string;url:string|null;fetched_at:string}[];operational_metrics:Record<string,Point[]>;thesis:{as_of_date:string;bull_case:string;base_case:string;bear_case:string;key_catalysts:string[];key_risks:string[]}|null};peers:Peer[]; }
interface ResearchReport { not_covered:boolean; unavailable:boolean; coverage_note?:string; published_at?:string;sections_total?:number;sections_with_real_content?:number;sections?:{title:string;content:string;has_real_content:boolean;missing_evidence:string[]}[]; }

const TABS:{id:Tab;label:string;icon:typeof BarChart3;requiresFull?:boolean}[]=[
  {id:"overview",label:"Overview",icon:Building2},{id:"business-model",label:"Business Model",icon:Briefcase},
  {id:"financials",label:"Financials",icon:FileText,requiresFull:true},
  {id:"kpis",label:"KPIs",icon:Activity,requiresFull:true},{id:"valuation",label:"Valuation",icon:Landmark,requiresFull:true},
  {id:"peers",label:"Peers",icon:Users,requiresFull:true},{id:"announcements",label:"Announcements",icon:MessageSquareText},
  {id:"filings",label:"Filings",icon:FolderOpen},{id:"ai",label:"AI Research",icon:Bot,requiresFull:true},{id:"report",label:"Report",icon:Download},
];
const latest=(series?:Point[])=>series?.length?series[series.length-1]:null;
const compact=(value:number|null|undefined)=>value==null?"—":new Intl.NumberFormat("en-PK",{notation:"compact",maximumFractionDigits:2}).format(value);
const pct=(value:number|null|undefined)=>value==null?"—":`${value.toFixed(2)}%`;
const ratioValue=(value:number|null|undefined,unit?:string)=>value==null?"—":unit==="%"?pct(value):`${value.toFixed(2)}${unit==="x"?"x":""}`;
const coverageText=(tier:CoverageTier)=>tier==="full"?"Source-verified fundamentals":tier==="unverified"?"Financials quarantined pending filing verification":"Price and announcement coverage only";
function Card({label,value,note}:{label:string;value:string;note?:string}){return <div className="rounded-xl border border-border bg-surface p-4"><p className="text-[10px] font-semibold uppercase tracking-wider text-muted">{label}</p><p className="mt-2 text-xl font-bold text-foreground">{value}</p>{note&&<p className="mt-1 text-xs text-muted">{note}</p>}</div>}

export function ComprehensiveResearchStudio(){
  const router=useRouter(); const [universe,setUniverse]=useState<Universe|null>(null); const [sector,setSector]=useState<"ALL"|"FERTILIZER"|"CEMENT">("ALL");
  const [query,setQuery]=useState("FFC"); const [workspace,setWorkspace]=useState<Workspace|null>(null); const [report,setReport]=useState<ResearchReport|null>(null);
  const [tab,setTab]=useState<Tab>("overview"); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{fetch(`${API}/research-workspace/universe`,{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}).then(setUniverse).catch(e=>setError(`Could not load the live research universe: ${e.message}`))},[]);
  const loadCompany=async(symbol:string)=>{const ticker=symbol.trim().toUpperCase();if(!ticker)return;setLoading(true);setError(null);setReport(null);setTab("overview");setQuery(ticker);try{const response=await fetch(`${API}/research-workspace/${encodeURIComponent(ticker)}`,{cache:"no-store"});if(!response.ok)throw new Error((await response.json()).detail??"Company research is unavailable");setWorkspace(await response.json())}catch(e){setWorkspace(null);setError(e instanceof Error?e.message:"Research request failed")}finally{setLoading(false)}};
  useEffect(()=>{
    fetch(`${API}/research-workspace/FFC`,{cache:"no-store"})
      .then(async response=>{if(!response.ok)throw new Error((await response.json()).detail??"Company research is unavailable");return response.json()})
      .then(data=>{setWorkspace(data);setLoading(false)})
      .catch(e=>{setError(e instanceof Error?e.message:"Research request failed");setLoading(false)});
  },[]);
  const filtered=useMemo(()=>(universe?.entries??[]).filter(e=>sector==="ALL"||e.sector===sector),[universe,sector]); const full=workspace?.coverage_tier==="full";
  const visibleTabs=TABS.filter(t=>!t.requiresFull||full); const financialRows=workspace?Object.entries(workspace.overview.financials).sort():[]; const ratioRows=workspace?Object.entries(workspace.overview.ratios).sort((a,b)=>a[1].category.localeCompare(b[1].category)):[];
  const submit=(event:FormEvent)=>{event.preventDefault();void loadCompany(query)};
  useEffect(()=>{
    if(tab!=="ai"||!workspace||report)return;
    fetch(`${API}/equity-research/${workspace.ticker}`,{cache:"no-store"})
      .then(async response=>response.ok?response.json():{not_covered:true,unavailable:true})
      .then(setReport)
      .catch(()=>setReport({not_covered:true,unavailable:true}));
  },[tab,workspace,report]);
  return <main className="min-h-screen bg-background px-4 py-6 text-foreground lg:px-8"><div className="mx-auto max-w-[1500px] space-y-5">
    <header className="rounded-2xl border border-border bg-gradient-to-r from-surface to-surface-alt p-6"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-accent">Khronos</p><h1 className="mt-1 text-3xl font-bold">Research Studio</h1><p className="mt-2 max-w-3xl text-sm text-muted">One evidence-first workspace for the complete PSX fertilizer and cement sectors: company intelligence, statements, KPIs, valuation, peers, filings, announcements, AI research and institutional delivery.</p></div>{universe&&<div className="grid grid-cols-3 gap-2 text-center"><Card label="Universe" value={String(universe.count)}/><Card label="Fertilizer" value={String(universe.sector_counts.FERTILIZER)}/><Card label="Cement" value={String(universe.sector_counts.CEMENT)}/></div>}</div>
      <form onSubmit={submit} className="mt-6 flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted"/><input value={query} onChange={e=>setQuery(e.target.value.toUpperCase())} placeholder="Enter FFC, EFERT, LUCK, DGKC..." className="w-full rounded-lg border border-border bg-background py-2.5 pl-10 pr-4 text-sm outline-none focus:border-accent"/></div><button className="rounded-lg bg-accent px-6 text-sm font-bold text-white disabled:opacity-50" disabled={loading}>{loading?<Loader2 className="h-4 w-4 animate-spin"/>:"Research"}</button></form>
      <div className="mt-4 flex flex-wrap gap-2">{(["ALL","FERTILIZER","CEMENT"] as const).map(s=><button key={s} onClick={()=>setSector(s)} className={`rounded-full px-3 py-1 text-xs font-semibold ${sector===s?"bg-accent text-white":"bg-background text-muted"}`}>{s==="ALL"?"All 23 companies":s}</button>)}</div>
      <div className="mt-3 flex max-h-24 flex-wrap gap-1.5 overflow-auto">{filtered.map(e=><button key={e.symbol} onClick={()=>void loadCompany(e.symbol)} title={`${e.name} — ${coverageText(e.coverage_tier)}`} className={`rounded border px-2 py-1 text-[11px] ${workspace?.ticker===e.symbol?"border-accent bg-accent/15 text-accent":"border-border text-muted hover:text-foreground"}`}>{e.symbol}<span className={`ml-1 ${e.coverage_tier==="full"?"text-positive":e.coverage_tier==="unverified"?"text-amber-400":"text-muted"}`}>●</span></button>)}</div>
    </header>
    {error&&<div className="rounded-xl border border-negative/40 bg-negative/10 p-4 text-sm text-negative">{error}</div>}
    {loading&&!workspace&&<div className="grid place-items-center py-24"><Loader2 className="h-8 w-8 animate-spin text-accent"/></div>}
    {workspace&&<><section className="rounded-2xl border border-border bg-surface p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-3"><h2 className="text-3xl font-black">{workspace.ticker}</h2><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold uppercase ${full?"bg-positive/15 text-positive":"bg-amber-400/15 text-amber-300"}`}>{workspace.coverage_tier.replace("_"," ")}</span></div><p className="mt-1 text-lg text-muted">{workspace.overview.issuer.name} · {workspace.overview.issuer.sector_name}</p><p className="mt-2 max-w-4xl text-sm text-muted">{workspace.overview.issuer.business_description??coverageText(workspace.coverage_tier)}</p></div><div className="flex gap-2"><button onClick={()=>router.push(`/trade-planning?ticker=${workspace.ticker}`)} className="flex items-center gap-2 rounded-lg bg-accent px-4 py-2 text-sm font-bold text-white"><TrendingUp className="h-4 w-4"/>Plan trade</button><a href={`${API}/research-workspace/${workspace.ticker}/report.pdf`} className="flex items-center gap-2 rounded-lg border border-border px-4 py-2 text-sm font-bold"><Download className="h-4 w-4"/>PDF</a></div></div>
      <div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-5"><Card label="Evidence sources" value={String(workspace.evidence.source_count)}/><Card label="Financial series" value={String(workspace.evidence.financial_series_count)}/><Card label="Ratio series" value={String(workspace.evidence.ratio_series_count)}/><Card label="Announcements" value={String(workspace.evidence.announcement_count)}/><Card label="Free float" value={pct(workspace.overview.free_float_pct)}/></div>{!full&&<div className="mt-4 rounded-lg border border-amber-400/30 bg-amber-400/10 p-3 text-sm text-amber-200"><b>Evidence control:</b> {coverageText(workspace.coverage_tier)}. Fundamentals-backed tabs and narrative are withheld until filing verification is complete.</div>}</section>
      <nav className="flex gap-1 overflow-x-auto border-b border-border">{visibleTabs.map(item=>{const Icon=item.icon;return <button key={item.id} onClick={()=>setTab(item.id)} className={`flex shrink-0 items-center gap-2 border-b-2 px-4 py-3 text-xs font-bold ${tab===item.id?"border-accent text-accent":"border-transparent text-muted"}`}><Icon className="h-4 w-4"/>{item.label}</button>})}</nav>
      {tab==="overview"&&<div className="grid gap-5 lg:grid-cols-3"><section className="rounded-xl border border-border bg-surface p-5 lg:col-span-2"><h3 className="font-bold">Company intelligence</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><Card label="Established" value={workspace.overview.issuer.establishment_year?.toString()??"—"}/><Card label="Fiscal year end" value={workspace.overview.issuer.fiscal_year_end_month?`Month ${workspace.overview.issuer.fiscal_year_end_month}`:"—"}/><Card label="Auditor" value={workspace.overview.issuer.auditor??"—"}/><Card label="Website" value={workspace.overview.issuer.website??"—"}/></div></section><section className="rounded-xl border border-border bg-surface p-5"><h3 className="font-bold">Research thesis</h3>{workspace.overview.thesis&&full?<div className="mt-4 space-y-3 text-sm"><p><b className="text-positive">Bull:</b> {workspace.overview.thesis.bull_case}</p><p><b className="text-accent">Base:</b> {workspace.overview.thesis.base_case}</p><p><b className="text-negative">Bear:</b> {workspace.overview.thesis.bear_case}</p></div>:<p className="mt-4 text-sm text-muted">No source-verified thesis is available.</p>}</section></div>}
      {tab==="business-model"&&<section className="rounded-xl border border-border bg-surface p-5"><BusinessModelSection ticker={workspace.ticker}/></section>}
      {tab==="financials"&&<section className="overflow-hidden rounded-xl border border-border bg-surface"><div className="border-b border-border p-5"><h3 className="font-bold">Financial statement explorer</h3><p className="text-xs text-muted">Reported periods from source-linked filings.</p></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-surface-alt text-muted"><tr><th className="p-3">Line item</th><th>Latest period</th><th>Value</th><th>Unit</th><th>Period type</th></tr></thead><tbody>{financialRows.map(([key,series])=>{const p=latest(series);return <tr key={key} className="border-t border-border"><td className="p-3 font-medium">{key.replaceAll("_"," ")}</td><td>{p?.period_end??"—"}</td><td className="font-mono">{compact(p?.value)}</td><td>{p?.unit??"—"}</td><td>{p?.period_type??"—"}</td></tr>})}</tbody></table></div></section>}
      {tab==="kpis"&&<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{ratioRows.filter(([,r])=>!r.category.toLowerCase().includes("valuation")).map(([key,r])=><Card key={key} label={`${r.category} · ${r.name}`} value={ratioValue(latest(r.values)?.value,r.unit)} note={r.formula}/>)}</div>}
      {tab==="valuation"&&<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{ratioRows.filter(([key,r])=>r.category.toLowerCase().includes("valuation")||["pe_ratio","pb_ratio","dividend_yield","ev_ebitda"].includes(key)).map(([key,r])=><Card key={key} label={r.name} value={ratioValue(latest(r.values)?.value,r.unit)} note={r.formula}/>)}</div>}
      {tab==="peers"&&<section className="overflow-hidden rounded-xl border border-border bg-surface"><div className="p-5"><h3 className="font-bold">{workspace.overview.issuer.sector_name} peer comparison</h3><p className="text-xs text-muted">Only source-verified values are used for analytical comparison.</p></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-surface-alt"><tr><th className="p-3">Ticker</th><th>Company</th><th>Coverage</th><th>Market cap</th><th>EPS</th><th>ROE</th><th>D/E</th><th>Net margin</th></tr></thead><tbody>{workspace.peers.map(p=><tr key={p.id} className="border-t border-border"><td className="p-3 font-bold text-accent">{p.symbol}</td><td>{p.name}</td><td>{p.coverage_status}</td><td>{compact(p.market_cap)}</td><td>{compact(p.eps)}</td><td>{pct(p.roe)}</td><td>{ratioValue(p.debt_to_equity,"x")}</td><td>{pct(p.net_profit_margin)}</td></tr>)}</tbody></table></div></section>}
      {tab==="announcements"&&<div className="space-y-3">{workspace.overview.announcements.map(a=><article key={a.id} className="rounded-xl border border-border bg-surface p-4"><div className="flex justify-between gap-4"><div><p className="text-xs font-bold uppercase text-accent">{a.category}</p><h3 className="mt-1 font-semibold">{a.title}</h3></div><time className="text-xs text-muted">{a.published_at.slice(0,10)}</time></div>{a.summary&&<p className="mt-2 text-sm text-muted">{a.summary}</p>}{a.source_url&&<a href={a.source_url} target="_blank" className="mt-2 inline-block text-xs text-accent">Open source ↗</a>}</article>)}{!workspace.overview.announcements.length&&<p className="rounded-xl border border-border bg-surface p-8 text-center text-muted">No announcements are stored for this issuer.</p>}</div>}
      {tab==="filings"&&<div className="grid gap-3 md:grid-cols-2">{workspace.overview.sources.map((s,i)=><article key={`${s.document_type}-${i}`} className="rounded-xl border border-border bg-surface p-4"><p className="font-semibold">{s.document_type.replaceAll("_"," ")}</p><p className="mt-1 text-xs text-muted">Tier {s.source_tier} · fetched {s.fetched_at.slice(0,10)}</p>{s.url?<a href={s.url} target="_blank" className="mt-3 inline-block text-xs text-accent">View filing/source ↗</a>:<p className="mt-3 text-xs text-muted">Local source record</p>}</article>)}</div>}
      {tab==="ai"&&<section className="rounded-xl border border-border bg-surface p-5"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-positive"/><h3 className="font-bold">Citation-grounded research report</h3></div>{!report?<Loader2 className="mt-8 h-6 w-6 animate-spin text-accent"/>:report.unavailable||report.not_covered?<p className="mt-4 text-sm text-muted">{report.coverage_note??"The citation-grounded research pipeline is currently unavailable for this ticker."}</p>:<div className="mt-5 space-y-4"><p className="text-xs text-muted">Evidence coverage: {report.sections_with_real_content}/{report.sections_total} sections · published {report.published_at?.slice(0,10)}</p>{report.sections?.map((s,i)=><article key={i} className="rounded-lg border border-border p-4"><h4 className="font-semibold">{s.title}</h4><p className="mt-2 whitespace-pre-wrap text-sm text-muted">{s.content}</p>{!s.has_real_content&&<p className="mt-2 text-xs text-amber-300">Missing evidence: {s.missing_evidence.join(", ")}</p>}</article>)}</div>}</section>}
      {tab==="report"&&<section className="rounded-xl border border-border bg-surface p-8 text-center"><Download className="mx-auto h-10 w-10 text-accent"/><h3 className="mt-3 text-xl font-bold">Institutional research delivery</h3><p className="mx-auto mt-2 max-w-2xl text-sm text-muted">Generate a print-ready PDF from the same live workspace payload, including coverage status, financial snapshot, thesis, announcements, source lineage and evidence limitations.</p><a href={`${API}/research-workspace/${workspace.ticker}/report.pdf`} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-accent px-5 py-2.5 text-sm font-bold text-white"><Download className="h-4 w-4"/>Download {workspace.ticker} report</a></section>}
    </>}</div></main>;
}
