"""add market_index and index_ohlcv tables

Revision ID: 0719cce11289
Revises: e4fdf1e396b9
Create Date: 2026-07-27 11:04:23.357311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0719cce11289'
down_revision: Union[str, None] = 'e4fdf1e396b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_index_code'), 'market_index', ['code'], unique=True)
    op.create_table('index_ohlcv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_index_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('is_delayed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['market_index_id'], ['market_index.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_index_id', 'trade_date', name='uq_index_ohlcv_index_date')
    )
    op.create_index(op.f('ix_index_ohlcv_market_index_id'), 'index_ohlcv', ['market_index_id'], unique=False)
    op.create_index(op.f('ix_index_ohlcv_trade_date'), 'index_ohlcv', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_index_ohlcv_trade_date'), table_name='index_ohlcv')
    op.drop_index(op.f('ix_index_ohlcv_market_index_id'), table_name='index_ohlcv')
    op.drop_table('index_ohlcv')
    op.drop_index(op.f('ix_market_index_code'), table_name='market_index')
    op.drop_table('market_index')
    # ### end Alembic commands ###
