"""add unique constraint on price_ohlcv security+trade_date

Revision ID: 26a2d7f7b309
Revises: 9086906824ff
Create Date: 2026-07-26 21:29:34.727407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26a2d7f7b309'
down_revision: Union[str, None] = '9086906824ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_price_ohlcv_security_date', 'price_ohlcv', ['security_id', 'trade_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_price_ohlcv_security_date', 'price_ohlcv', type_='unique')
    # ### end Alembic commands ###
