"""add unique constraint on macro_observation series+period

Revision ID: ae8e0f27100e
Revises: 26a2d7f7b309
Create Date: 2026-07-27 00:13:08.103140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae8e0f27100e'
down_revision: Union[str, None] = '26a2d7f7b309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_macro_observation_series_period', 'macro_observation', ['macro_series_id', 'period'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_macro_observation_series_period', 'macro_observation', type_='unique')
    # ### end Alembic commands ###
