"""add ml_signal_score table

Revision ID: c06ca6bf399c
Revises: c8f2a1d5e9b3
Create Date: 2026-08-12 18:19:09.014754

Adds ml_signal_score, the output table for the new walk-forward-validated
calibrated ML classifier (app/etl/ml_signal_engine.py). Kept separate from
signal_score (the rules-based engine) -- different evidence class, never
conflated in one row. Pooled validation metrics are denormalized onto every
row of a given run so each row is a self-contained, auditable record. See
app/db/models/scoring.py's MlSignalScore docstring.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06ca6bf399c'
down_revision: Union[str, None] = 'c8f2a1d5e9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_signal_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('model_version', sa.Integer(), nullable=False),
    sa.Column('signal', sa.String(length=20), nullable=False),
    sa.Column('outperformance_probability', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('validation_observations', sa.Integer(), nullable=True),
    sa.Column('validation_accuracy', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('validation_buy_precision', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('validation_sell_precision', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('validation_brier_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('validation_roc_auc', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_signal_score_as_of_date'), 'ml_signal_score', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_ml_signal_score_issuer_id'), 'ml_signal_score', ['issuer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_signal_score_issuer_id'), table_name='ml_signal_score')
    op.drop_index(op.f('ix_ml_signal_score_as_of_date'), table_name='ml_signal_score')
    op.drop_table('ml_signal_score')
    # ### end Alembic commands ###
