"""add operational_metric, capm_assumption, thesis tables

Revision ID: e4fdf1e396b9
Revises: 80b3ce5c9055
Create Date: 2026-07-27 01:24:41.637926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4fdf1e396b9'
down_revision: Union[str, None] = '80b3ce5c9055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capm_assumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('risk_free_rate_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('beta', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('base_equity_risk_premium_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('country_risk_premium_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('source_note', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capm_assumption_as_of_date'), 'capm_assumption', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_capm_assumption_issuer_id'), 'capm_assumption', ['issuer_id'], unique=False)
    op.create_table('operational_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.Column('metric_key', sa.String(length=60), nullable=False),
    sa.Column('product', sa.String(length=40), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuer.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issuer_id', 'metric_key', 'product', 'period_end', name='uq_operational_metric_issuer_key_product_period')
    )
    op.create_index(op.f('ix_operational_metric_issuer_id'), 'operational_metric', ['issuer_id'], unique=False)
    op.create_index(op.f('ix_operational_metric_metric_key'), 'operational_metric', ['metric_key'], unique=False)
    op.create_index(op.f('ix_operational_metric_period_end'), 'operational_metric', ['period_end'], unique=False)
    op.create_table('thesis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('bull_case', sa.Text(), nullable=False),
    sa.Column('base_case', sa.Text(), nullable=False),
    sa.Column('bear_case', sa.Text(), nullable=False),
    sa.Column('key_catalysts', sa.JSON(), nullable=False),
    sa.Column('key_risks', sa.JSON(), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuer.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thesis_as_of_date'), 'thesis', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_thesis_issuer_id'), 'thesis', ['issuer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thesis_issuer_id'), table_name='thesis')
    op.drop_index(op.f('ix_thesis_as_of_date'), table_name='thesis')
    op.drop_table('thesis')
    op.drop_index(op.f('ix_operational_metric_period_end'), table_name='operational_metric')
    op.drop_index(op.f('ix_operational_metric_metric_key'), table_name='operational_metric')
    op.drop_index(op.f('ix_operational_metric_issuer_id'), table_name='operational_metric')
    op.drop_table('operational_metric')
    op.drop_index(op.f('ix_capm_assumption_issuer_id'), table_name='capm_assumption')
    op.drop_index(op.f('ix_capm_assumption_as_of_date'), table_name='capm_assumption')
    op.drop_table('capm_assumption')
    # ### end Alembic commands ###
