"""add external identity map table

Revision ID: 048788e792ac
Revises: c06ca6bf399c
Create Date: 2026-08-23 10:11:39.963753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '048788e792ac'
down_revision: Union[str, None] = 'c06ca6bf399c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_identity_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.Column('external_system', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('external_security_id', sa.String(length=64), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('match_method', sa.String(length=30), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_system', 'external_id', name='uq_identity_map_system_external_id'),
    sa.UniqueConstraint('issuer_id', 'external_system', name='uq_identity_map_issuer_system')
    )
    op.create_index(op.f('ix_external_identity_map_external_system'), 'external_identity_map', ['external_system'], unique=False)
    op.create_index(op.f('ix_external_identity_map_issuer_id'), 'external_identity_map', ['issuer_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected a pre-existing, unrelated drift on analyst_packet
    # (a unique constraint vs. unique index mismatch between the model and the live DB) --
    # deliberately left out of this migration since it's outside this change's scope and its
    # root cause hasn't been investigated. Worth its own migration if it's a real issue.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_identity_map_issuer_id'), table_name='external_identity_map')
    op.drop_index(op.f('ix_external_identity_map_external_system'), table_name='external_identity_map')
    op.drop_table('external_identity_map')
    # ### end Alembic commands ###
