"""add company profile fields to issuer

Revision ID: 80b3ce5c9055
Revises: ae8e0f27100e
Create Date: 2026-07-27 01:05:26.565395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b3ce5c9055'
down_revision: Union[str, None] = 'ae8e0f27100e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issuer', sa.Column('business_description', sa.Text(), nullable=True))
    op.add_column('issuer', sa.Column('address', sa.String(length=300), nullable=True))
    op.add_column('issuer', sa.Column('website', sa.String(length=200), nullable=True))
    op.add_column('issuer', sa.Column('registrar', sa.String(length=300), nullable=True))
    op.add_column('issuer', sa.Column('auditor', sa.String(length=200), nullable=True))
    op.add_column('issuer', sa.Column('fiscal_year_end_month', sa.Integer(), nullable=True))
    op.add_column('issuer', sa.Column('is_psx_listed', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issuer', 'is_psx_listed')
    op.drop_column('issuer', 'fiscal_year_end_month')
    op.drop_column('issuer', 'auditor')
    op.drop_column('issuer', 'registrar')
    op.drop_column('issuer', 'website')
    op.drop_column('issuer', 'address')
    op.drop_column('issuer', 'business_description')
    # ### end Alembic commands ###
