"""initial schema

Revision ID: 9086906824ff
Revises: 
Create Date: 2026-07-26 20:20:47.456825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9086906824ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macro_series_code'), 'macro_series', ['code'], unique=True)
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_full_name'), 'person', ['full_name'], unique=False)
    op.create_table('ratio_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('formula_version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('formula_description', sa.String(length=500), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratio_definition_key'), 'ratio_definition', ['key'], unique=False)
    op.create_table('sector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('psx_sector_code', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sector_name'), 'sector', ['name'], unique=True)
    op.create_table('issuer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=60), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('ultimate_parent_issuer_id', sa.Integer(), nullable=True),
    sa.Column('incorporation_date', sa.Date(), nullable=True),
    sa.Column('is_conglomerate', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.ForeignKeyConstraint(['ultimate_parent_issuer_id'], ['issuer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issuer_name'), 'issuer', ['name'], unique=True)
    op.create_table('macro_observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('macro_series_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['macro_series_id'], ['macro_series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macro_observation_macro_series_id'), 'macro_observation', ['macro_series_id'], unique=False)
    op.create_index(op.f('ix_macro_observation_period'), 'macro_observation', ['period'], unique=False)
    op.create_table('sector_risk_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('overall_risk', sa.String(length=20), nullable=False),
    sa.Column('geopolitical', sa.String(length=30), nullable=False),
    sa.Column('economy', sa.String(length=30), nullable=False),
    sa.Column('imf_program', sa.String(length=30), nullable=False),
    sa.Column('currency_pkr', sa.String(length=30), nullable=False),
    sa.Column('key_positives', sa.JSON(), nullable=False),
    sa.Column('key_negatives', sa.JSON(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sector_risk_snapshot_as_of_date'), 'sector_risk_snapshot', ['as_of_date'], unique=False)
    op.create_table('board_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_independent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuer.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_membership_issuer_id'), 'board_membership', ['issuer_id'], unique=False)
    op.create_index(op.f('ix_board_membership_person_id'), 'board_membership', ['person_id'], unique=False)
    op.create_table('ratio_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ratio_definition_id', sa.Integer(), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('input_fact_ids', sa.JSON(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuer.id'], ),
    sa.ForeignKeyConstraint(['ratio_definition_id'], ['ratio_definition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratio_value_issuer_id'), 'ratio_value', ['issuer_id'], unique=False)
    op.create_index(op.f('ix_ratio_value_period_end'), 'ratio_value', ['period_end'], unique=False)
    op.create_index(op.f('ix_ratio_value_ratio_definition_id'), 'ratio_value', ['ratio_definition_id'], unique=False)
    op.create_table('security',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('security_type', sa.String(length=40), nullable=False),
    sa.Column('listing_status', sa.String(length=20), nullable=False),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('free_float_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_issuer_id'), 'security', ['issuer_id'], unique=False)
    op.create_index(op.f('ix_security_symbol'), 'security', ['symbol'], unique=True)
    op.create_table('signal_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('growth_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('financial_health_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('valuation_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('catalyst_risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('composite_signal', sa.String(length=20), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('suppression_reasons', sa.JSON(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_score_as_of_date'), 'signal_score', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_signal_score_issuer_id'), 'signal_score', ['issuer_id'], unique=False)
    op.create_table('source_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('document_type', sa.String(length=60), nullable=False),
    sa.Column('source_tier', sa.String(length=30), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_document_content_hash'), 'source_document', ['content_hash'], unique=True)
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('summary', sa.String(length=1000), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuer.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcement_issuer_id'), 'announcement', ['issuer_id'], unique=False)
    op.create_index(op.f('ix_announcement_published_at'), 'announcement', ['published_at'], unique=False)
    op.create_table('corporate_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('announced_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('ratio_or_amount', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporate_action_effective_date'), 'corporate_action', ['effective_date'], unique=False)
    op.create_index(op.f('ix_corporate_action_security_id'), 'corporate_action', ['security_id'], unique=False)
    op.create_table('extraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_source_document_id'), 'extraction', ['source_document_id'], unique=False)
    op.create_table('price_ohlcv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('trades', sa.Integer(), nullable=True),
    sa.Column('adjusted', sa.Boolean(), nullable=False),
    sa.Column('adjustment_method', sa.String(length=60), nullable=True),
    sa.Column('circuit_upper', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('circuit_lower', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('is_delayed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_ohlcv_security_id'), 'price_ohlcv', ['security_id'], unique=False)
    op.create_index(op.f('ix_price_ohlcv_trade_date'), 'price_ohlcv', ['trade_date'], unique=False)
    op.create_table('ticker_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('old_symbol', sa.String(length=20), nullable=False),
    sa.Column('new_symbol', sa.String(length=20), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticker_history_security_id'), 'ticker_history', ['security_id'], unique=False)
    op.create_table('entity_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=True),
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('resolved_by', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcement.id'], ),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuer.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_link_issuer_id'), 'entity_link', ['issuer_id'], unique=False)
    op.create_table('evidence_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_class', sa.String(length=30), nullable=False),
    sa.Column('target_table', sa.String(length=60), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('extraction_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extraction.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_fact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.Column('line_item', sa.String(length=80), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=True),
    sa.Column('is_restated', sa.Boolean(), nullable=False),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extraction.id'], ),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuer.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['financial_fact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_fact_issuer_id'), 'financial_fact', ['issuer_id'], unique=False)
    op.create_index(op.f('ix_financial_fact_line_item'), 'financial_fact', ['line_item'], unique=False)
    op.create_index(op.f('ix_financial_fact_period_end'), 'financial_fact', ['period_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_fact_period_end'), table_name='financial_fact')
    op.drop_index(op.f('ix_financial_fact_line_item'), table_name='financial_fact')
    op.drop_index(op.f('ix_financial_fact_issuer_id'), table_name='financial_fact')
    op.drop_table('financial_fact')
    op.drop_table('evidence_link')
    op.drop_index(op.f('ix_entity_link_issuer_id'), table_name='entity_link')
    op.drop_table('entity_link')
    op.drop_index(op.f('ix_ticker_history_security_id'), table_name='ticker_history')
    op.drop_table('ticker_history')
    op.drop_index(op.f('ix_price_ohlcv_trade_date'), table_name='price_ohlcv')
    op.drop_index(op.f('ix_price_ohlcv_security_id'), table_name='price_ohlcv')
    op.drop_table('price_ohlcv')
    op.drop_index(op.f('ix_extraction_source_document_id'), table_name='extraction')
    op.drop_table('extraction')
    op.drop_index(op.f('ix_corporate_action_security_id'), table_name='corporate_action')
    op.drop_index(op.f('ix_corporate_action_effective_date'), table_name='corporate_action')
    op.drop_table('corporate_action')
    op.drop_index(op.f('ix_announcement_published_at'), table_name='announcement')
    op.drop_index(op.f('ix_announcement_issuer_id'), table_name='announcement')
    op.drop_table('announcement')
    op.drop_index(op.f('ix_source_document_content_hash'), table_name='source_document')
    op.drop_table('source_document')
    op.drop_index(op.f('ix_signal_score_issuer_id'), table_name='signal_score')
    op.drop_index(op.f('ix_signal_score_as_of_date'), table_name='signal_score')
    op.drop_table('signal_score')
    op.drop_index(op.f('ix_security_symbol'), table_name='security')
    op.drop_index(op.f('ix_security_issuer_id'), table_name='security')
    op.drop_table('security')
    op.drop_index(op.f('ix_ratio_value_ratio_definition_id'), table_name='ratio_value')
    op.drop_index(op.f('ix_ratio_value_period_end'), table_name='ratio_value')
    op.drop_index(op.f('ix_ratio_value_issuer_id'), table_name='ratio_value')
    op.drop_table('ratio_value')
    op.drop_index(op.f('ix_board_membership_person_id'), table_name='board_membership')
    op.drop_index(op.f('ix_board_membership_issuer_id'), table_name='board_membership')
    op.drop_table('board_membership')
    op.drop_index(op.f('ix_sector_risk_snapshot_as_of_date'), table_name='sector_risk_snapshot')
    op.drop_table('sector_risk_snapshot')
    op.drop_index(op.f('ix_macro_observation_period'), table_name='macro_observation')
    op.drop_index(op.f('ix_macro_observation_macro_series_id'), table_name='macro_observation')
    op.drop_table('macro_observation')
    op.drop_index(op.f('ix_issuer_name'), table_name='issuer')
    op.drop_table('issuer')
    op.drop_index(op.f('ix_sector_name'), table_name='sector')
    op.drop_table('sector')
    op.drop_index(op.f('ix_ratio_definition_key'), table_name='ratio_definition')
    op.drop_table('ratio_definition')
    op.drop_index(op.f('ix_person_full_name'), table_name='person')
    op.drop_table('person')
    op.drop_index(op.f('ix_macro_series_code'), table_name='macro_series')
    op.drop_table('macro_series')
    # ### end Alembic commands ###
