"use client";

import React, { useState } from 'react';
import { PSXNewsItem, MacroIndicator, SectorSentiment } from './types';
import { X, Copy, Download, Check, FileText, Sparkles } from 'lucide-react';

interface ExportReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  newsItems: PSXNewsItem[];
  macroIndicators: MacroIndicator[];
  sectorSentiment: SectorSentiment[];
}

export const ExportReportModal: React.FC<ExportReportModalProps> = ({
  isOpen,
  onClose,
  newsItems,
  macroIndicators,
  sectorSentiment
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const todayStr = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const reportMarkdown = `# PAK-QUANT WORLDMONITOR: PSX INTELLIGENCE & MACRO REPORT
**Date:** ${todayStr}
**Terminal Build:** Quant Engine v3.6
**Target Audience:** PSX Traders, Quants & Institutional Portfolio Managers

---

## 1. MACROECONOMIC & MARKET DASHBOARD
${macroIndicators.map(ind => `- **${ind.name} (${ind.tickerSymbol || 'MACRO'}):** ${ind.value} (${ind.change}) — *${ind.description}*`).join('\n')}

---

## 2. SECTOR SENTIMENT & TRANSMISSION MATRIX
${sectorSentiment.map(sec => `- **${sec.sector}**: [${sec.sentiment} | Score: ${sec.score}] — Key Driver: ${sec.keyDriver} (Top Tickers: ${sec.topTickers.join(', ')})`).join('\n')}

---

## 3. REAL-TIME GEOPOLITICAL & PSX INTELLIGENCE HEADLINES
${newsItems.map((news, idx) => `
### ${idx + 1}. ${news.title}
- **Category:** ${news.category} | **Sentiment:** ${news.sentimentScore} ${news.sentiment} | **Impact Horizon:** ${news.impactHorizon}
- **Affected Tickers:** ${news.tickers.map(t => `$${t}`).join(', ')}
- **Executive Summary:** ${news.summary}
- **Financial Transmission:** ${news.aiAnalysis}
- **Quant Projection (Expected Index Delta: ${news.trendProjection?.expectedIndexDelta || 'N/A'}):**
  - *Bull Case (${news.trendProjection?.probabilityBull || 60}%):* ${news.trendProjection?.bullCase}
  - *Base Case:* ${news.trendProjection?.baseCase}
  - *Bear Case (${news.trendProjection?.probabilityBear || 20}%):* ${news.trendProjection?.bearCase}
`).join('\n')}

---
*Report generated by PSX WorldMonitor Quant Terminal.*
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(reportMarkdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([reportMarkdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `PSX_WorldMonitor_Report_${new Date().toISOString().slice(0, 10)}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-md flex items-center justify-center p-4">
      <div className="bg-[#0e131f] border border-slate-800 rounded-2xl max-w-3xl w-full max-h-[90vh] flex flex-col shadow-2xl p-6 font-mono space-y-4">

        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <div className="flex items-center space-x-2">
            <FileText className="w-5 h-5 text-emerald-400" />
            <h3 className="text-base font-bold text-slate-100">
              Export PSX Quant & Trader Intelligence Magazine Report
            </h3>
          </div>
          <button onClick={onClose} className="text-slate-400 hover:text-white font-bold">
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto bg-[#0a0d14] border border-slate-800 rounded-xl p-4 font-mono text-xs text-slate-300 whitespace-pre-wrap leading-relaxed shadow-inner">
          {reportMarkdown}
        </div>

        <div className="flex items-center justify-between pt-3 border-t border-slate-800">
          <span className="text-[11px] text-slate-400">
            Export ready in Markdown format for reports or client briefings.
          </span>

          <div className="flex items-center space-x-3">
            <button
              onClick={handleCopy}
              className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-bold rounded-lg flex items-center space-x-1.5 transition-all"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
              <span>{copied ? 'Copied Markdown' : 'Copy Markdown'}</span>
            </button>

            <button
              onClick={handleDownload}
              className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold rounded-lg flex items-center space-x-1.5 shadow-lg transition-all"
            >
              <Download className="w-4 h-4" />
              <span>Download .MD File</span>
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};
