import {
  Landmark, Flame, Monitor, Layers, Sprout, Zap, Building2,
  Truck, Car, ShoppingCart, TrendingUp, Activity, Droplets,
  Shield, Leaf, Settings, Home, FileText, Package, Bus,
  type LucideIcon,
} from "lucide-react";

export interface SectorConfig {
  slug: string;
  name: string;
  href: string;
  hasData: boolean;          // true = pilot sector with real backend data
  companies: number;
  icon: LucideIcon;
  color: string;
  description: string;
  gdpSharePct: number;
  psxWeightPct: number;
  marketCapPkrBn: number;
  exportSharePct: number;
  specializedMetrics: string;
}

export const SECTORS: SectorConfig[] = [
  {
    slug: "commercial-banks",
    name: "Commercial Banks",
    href: "/sector/commercial-banks",
    hasData: false,
    companies: 21,
    icon: Landmark,
    color: "blue",
    description:
      "The banking sector is the largest component of the KSE-100, providing credit across the economy. Key drivers include the interest-rate cycle, CASA ratio, PIB/T-bill holdings, and NPL trajectory.",
    gdpSharePct: 7.8,
    psxWeightPct: 20.1,
    marketCapPkrBn: 920,
    exportSharePct: 0,
    specializedMetrics: "Deposits, net advances, NIM, ADR, infection ratio, CAR, CASA ratio",
  },
  {
    slug: "oil-gas-ep",
    name: "Oil & Gas E&P",
    href: "/sector/oil-gas-ep",
    hasData: false,
    companies: 4,
    icon: Flame,
    color: "orange",
    description:
      "Exploration & production of crude oil and natural gas. Key drivers include Brent crude prices, wellhead pricing, production decline curves, and government royalty structure.",
    gdpSharePct: 4.5,
    psxWeightPct: 16.2,
    marketCapPkrBn: 1250,
    exportSharePct: 0,
    specializedMetrics: "Production (boe/day), 2P reserves, wellhead price, depletion rate, capex/boe",
  },
  {
    slug: "technology-communication",
    name: "Technology & Communication",
    href: "/sector/technology-communication",
    hasData: false,
    companies: 32,
    icon: Monitor,
    color: "purple",
    description:
      "IT services, telecom operators, and digital infrastructure. Key drivers include PKR depreciation (IT export tailwind), cellular subscribers, data ARPU, and government digitization spend.",
    gdpSharePct: 3.5,
    psxWeightPct: 7.4,
    marketCapPkrBn: 620,
    exportSharePct: 4.5,
    specializedMetrics: "IT exports (USD mn), subscribers, ARPU, data revenue share, headcount growth",
  },
  {
    slug: "textile-composite",
    name: "Textile Composite",
    href: "/sector/textile-composite",
    hasData: false,
    companies: 41,
    icon: Layers,
    color: "cyan",
    description:
      "Pakistan's largest export sector covering spinning, weaving, and composite mills. Key drivers include cotton prices, energy tariffs, global demand, and SBP TERF/LTFF concessional financing.",
    gdpSharePct: 8.5,
    psxWeightPct: 5.8,
    marketCapPkrBn: 540,
    exportSharePct: 55.0,
    specializedMetrics: "Yarn counts, cloth production (m sq m), export volumes, cotton procurement, energy cost",
  },
  {
    slug: "fertilizer",
    name: "Fertilizer",
    href: "/sector/fertilizer",
    hasData: true,
    companies: 7,
    icon: Sprout,
    color: "emerald",
    description:
      "Critical to Pakistan's agriculture economy, producing urea and DAP. Key drivers include gas feedstock pricing, SBP policy rate, government offtake subsidies, and crop-cycle demand.",
    gdpSharePct: 3.2,
    psxWeightPct: 4.8,
    marketCapPkrBn: 485,
    exportSharePct: 1.8,
    specializedMetrics: "Capacity (tons/day), production volumes, offtake, gas pricing, urea market share",
  },
  {
    slug: "power-generation",
    name: "Power Generation & Distribution",
    href: "/sector/power-generation",
    hasData: false,
    companies: 12,
    icon: Zap,
    color: "amber",
    description:
      "IPPs and distribution companies supplying electricity via the national grid. Key drivers include capacity payments, fuel cost pass-through, NTDC offtake, and IMF-driven circular debt resolution.",
    gdpSharePct: 2.8,
    psxWeightPct: 4.3,
    marketCapPkrBn: 390,
    exportSharePct: 0,
    specializedMetrics: "Generation capacity (MW), plant load factor, fuel mix, NTDC receivables, capacity payments",
  },
  {
    slug: "cement",
    name: "Cement",
    href: "/sector/cement",
    hasData: true,
    companies: 18,
    icon: Building2,
    color: "gray",
    description:
      "Serves domestic construction, infrastructure, and export markets. Key drivers include housing demand, government PSDP spending, coal and gas input costs, and retention pricing.",
    gdpSharePct: 1.5,
    psxWeightPct: 3.1,
    marketCapPkrBn: 312,
    exportSharePct: 2.1,
    specializedMetrics: "Dispatches (local+export), capacity utilization, coal cost, retention price, clinker production",
  },
  {
    slug: "oil-gas-marketing",
    name: "Oil & Gas Marketing",
    href: "/sector/oil-gas-marketing",
    hasData: false,
    companies: 5,
    icon: Truck,
    color: "orange",
    description:
      "Marketing and distribution of petroleum products. Key metrics include POL volumes, gross margin per litre, and circular-debt government receivables.",
    gdpSharePct: 2.1,
    psxWeightPct: 3.4,
    marketCapPkrBn: 320,
    exportSharePct: 0,
    specializedMetrics: "Volumes (m litres), gross margin/litre, circular debt receivables, storage infrastructure",
  },
  {
    slug: "automobile",
    name: "Automobile Assembler",
    href: "/sector/automobile",
    hasData: false,
    companies: 5,
    icon: Car,
    color: "rose",
    description:
      "Assembly of passenger cars, LCVs, and trucks under Pakistan's localisation policy regime. Key drivers include consumer financing rates, CKD duty structure, and total industry volumes.",
    gdpSharePct: 1.8,
    psxWeightPct: 3.2,
    marketCapPkrBn: 298,
    exportSharePct: 0.5,
    specializedMetrics: "Units assembled, localization %, CKD duty impact, industry volumes, auto financing penetration",
  },
  {
    slug: "food-personal-care",
    name: "Food & Personal Care",
    href: "/sector/food-personal-care",
    hasData: false,
    companies: 22,
    icon: ShoppingCart,
    color: "lime",
    description:
      "Consumer staples including packaged food, beverages, and personal care products. Key drivers include commodity input prices, consumer spending power, and organised retail penetration.",
    gdpSharePct: 2.4,
    psxWeightPct: 2.8,
    marketCapPkrBn: 260,
    exportSharePct: 2.3,
    specializedMetrics: "Volume growth, commodity input costs, consumer pricing power, gross margin trajectory",
  },
  {
    slug: "investment-companies",
    name: "Investment Companies",
    href: "/sector/investment-companies",
    hasData: false,
    companies: 22,
    icon: TrendingUp,
    color: "blue",
    description:
      "Closed-end funds and holding companies with cross-sector equity stakes. Key metrics include NAV discount, portfolio composition, dividend payout policy, and leverage.",
    gdpSharePct: 1.2,
    psxWeightPct: 2.3,
    marketCapPkrBn: 214,
    exportSharePct: 0,
    specializedMetrics: "NAV, discount to NAV, dividend yield, portfolio composition, leverage ratio",
  },
  {
    slug: "pharmaceutical",
    name: "Pharmaceutical",
    href: "/sector/pharmaceutical",
    hasData: false,
    companies: 11,
    icon: Activity,
    color: "emerald",
    description:
      "Generic and branded drug manufacturing. Key drivers include DRAP price regulation, active pharmaceutical ingredient (API) import costs, and public sector procurement.",
    gdpSharePct: 1.2,
    psxWeightPct: 2.1,
    marketCapPkrBn: 195,
    exportSharePct: 0.8,
    specializedMetrics: "Product mix (generics/branded), API import costs, DRAP price regulation, export volumes",
  },
  {
    slug: "chemical",
    name: "Chemical",
    href: "/sector/chemical",
    hasData: false,
    companies: 19,
    icon: Droplets,
    color: "teal",
    description:
      "Petrochemicals, industrial chemicals, and specialty products. Key drivers include feedstock (naphtha, natural gas) prices and downstream demand from textiles and agriculture.",
    gdpSharePct: 1.1,
    psxWeightPct: 1.8,
    marketCapPkrBn: 168,
    exportSharePct: 1.2,
    specializedMetrics: "Feedstock pricing, product mix, export volumes, capacity utilization, downstream linkage",
  },
  {
    slug: "insurance",
    name: "Insurance",
    href: "/sector/insurance",
    hasData: false,
    companies: 25,
    icon: Shield,
    color: "purple",
    description:
      "Life, non-life, and health insurance. Key drivers include gross premium growth, combined ratio, investment income on float, and expansion of bancassurance channels.",
    gdpSharePct: 0.8,
    psxWeightPct: 1.5,
    marketCapPkrBn: 140,
    exportSharePct: 0,
    specializedMetrics: "Gross premium, combined ratio, investment income, claims ratio, bancassurance growth",
  },
  {
    slug: "sugar-allied",
    name: "Sugar & Allied",
    href: "/sector/sugar-allied",
    hasData: false,
    companies: 19,
    icon: Leaf,
    color: "lime",
    description:
      "Sugar crushing and by-products including ethanol and bagasse-based co-generation. Key drivers include seasonal crushing (Oct–Mar), sugarcane support price, and export/ethanol quota policy.",
    gdpSharePct: 0.7,
    psxWeightPct: 0.9,
    marketCapPkrBn: 84,
    exportSharePct: 1.5,
    specializedMetrics: "Crushing season (Oct–Mar), sugarcane procurement price, ethanol production, export quota",
  },
  {
    slug: "engineering",
    name: "Engineering",
    href: "/sector/engineering",
    hasData: false,
    companies: 15,
    icon: Settings,
    color: "gray",
    description:
      "Capital goods, electric equipment, and industrial machinery. Key drivers include government PSDP development expenditure, energy sector capex cycles, and construction activity.",
    gdpSharePct: 0.9,
    psxWeightPct: 1.1,
    marketCapPkrBn: 102,
    exportSharePct: 0.4,
    specializedMetrics: "Order backlog, PSDP spend exposure, government contracts, capacity utilization, capex trends",
  },
  {
    slug: "real-estate",
    name: "Real Estate / REITs",
    href: "/sector/real-estate",
    hasData: false,
    companies: 10,
    icon: Home,
    color: "amber",
    description:
      "Property developers and listed REITs. Key drivers include the interest rate cycle, rental yields, REIT regulatory development, and government housing schemes.",
    gdpSharePct: 2.1,
    psxWeightPct: 1.3,
    marketCapPkrBn: 121,
    exportSharePct: 0,
    specializedMetrics: "Rental yield, occupancy rate, property valuations, development pipeline, REIT NAV",
  },
  {
    slug: "transport",
    name: "Transport",
    href: "/sector/transport",
    hasData: false,
    companies: 5,
    icon: Bus,
    color: "cyan",
    description:
      "Road, air, and logistics companies. Key drivers include fuel costs, freight rates, Karachi port throughput, and government infrastructure investment under CPEC.",
    gdpSharePct: 3.8,
    psxWeightPct: 1.2,
    marketCapPkrBn: 112,
    exportSharePct: 0,
    specializedMetrics: "Fleet utilization, fuel cost/km, freight rates, port throughput, route profitability",
  },
  {
    slug: "paper-board",
    name: "Paper & Board",
    href: "/sector/paper-board",
    hasData: false,
    companies: 5,
    icon: FileText,
    color: "gray",
    description:
      "Paper manufacturing and packaging products. Key drivers include wastepaper import costs, energy tariffs, and downstream packaging demand from FMCG companies.",
    gdpSharePct: 0.3,
    psxWeightPct: 0.4,
    marketCapPkrBn: 37,
    exportSharePct: 0.2,
    specializedMetrics: "Production volume (tons), wastepaper input cost, energy intensity, FMCG packaging demand",
  },
  {
    slug: "tobacco",
    name: "Tobacco",
    href: "/sector/tobacco",
    hasData: false,
    companies: 2,
    icon: Package,
    color: "rose",
    description:
      "Cigarette manufacturing under excise-driven revenue models. Key drivers include illicit trade volumes, annual FED revisions, consumer down-trading, and plain-packaging regulation.",
    gdpSharePct: 0.4,
    psxWeightPct: 0.7,
    marketCapPkrBn: 65,
    exportSharePct: 0.1,
    specializedMetrics: "Volume (sticks sold), illicit trade share, FED structure, pricing power, regulatory pipeline",
  },
];

export const SECTOR_BY_SLUG = Object.fromEntries(SECTORS.map((s) => [s.slug, s]));

export const COLOR: Record<string, { box: string; icon: string }> = {
  blue:    { box: "bg-[#10161A]",         icon: "text-[#DAE1EE]" },
  emerald: { box: "bg-[#566680]",         icon: "text-[#DAE1EE]" },
  orange:  { box: "bg-[#8E9CB7]/35 border border-[#8E9CB7]/40", icon: "text-[#10161A]" },
  purple:  { box: "bg-[#B4C0D5]/50 border border-white/60",     icon: "text-[#566680]" },
  amber:   { box: "bg-[#566680]/20 border border-[#566680]/30", icon: "text-[#10161A]" },
  rose:    { box: "bg-[#10161A]/10 border border-[#10161A]/20", icon: "text-[#566680]" },
  teal:    { box: "bg-[#8E9CB7]/25 border border-white/80",     icon: "text-[#10161A]" },
  gray:    { box: "bg-white/80 border border-white",            icon: "text-[#566680]" },
  cyan:    { box: "bg-[#B4C0D5]/40 border border-[#8E9CB7]/30", icon: "text-[#10161A]" },
  lime:    { box: "bg-[#566680]/15 border border-[#566680]/20", icon: "text-[#566680]" },
};
